class_path: models.RandomModSigModel
init_args:
  n_frames: 1501
  temp_params:
    add_lfo:
      dim: 1
    sub_lfo:
      dim: 1
    env:
      dim: 1
  mod_sig_gen:
    class_path: modulations.ModSignalGenRandomBezier2D
    init_args:
      min_n_seg: 24
      max_n_seg: 24
      min_degree: 3
      max_degree: 3
      min_seg_interval_frac: 0.0
      is_c1_cont: false
      normalize: false
      eps: 1.0e-8
