custom:
  project_name: mod_discovery
  model_name: mss__s24d3D_rand__sm_16_1024
  dataset_name: ase__ableton_10
  cpu_batch_size: 5
  use_wandb_cpu: false
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [3]
  max_epochs: 30
  num_sanity_val_steps: 1
  gradient_clip_val: 0.5

data:
  class_path: mod_discovery.data_modules.SeedDataModule
  init_args:
    batch_size: 32
    ac: misc/audio_config.yml
    n_seeds: 1024
    mod_sig_gens:
      - class_path: mod_discovery.modulations.ModSignalGenRandomBezier1D
        init_args:
          min_n_seg: 1
          max_n_seg: 8
          min_degree: 1
          max_degree: 3
          min_seg_interval_frac: 0.5
    global_param_names:
      - q
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    n_frames: 1501
    num_workers: 4

model:
  class_path: mod_discovery.lightning.ModDiscoveryLightingModule
  init_args:
    ac: misc/audio_config.yml
    spectral_visualizer: misc/log_mel_spec.yml
    synth: synths/synth__ase.yml
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    interp_temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    model: models/spectral_2dcnn_dd50__ase__sm.yml
    temp_param_names_hat:
      - add_lfo
      - sub_lfo
      - env
    interp_temp_param_names_hat:
      - add_lfo
      - env
    synth_hat: synths/synth__ase__sm.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss

    synth_opt: ../opt/sf_adam_w__lr_5e-2.yml
    model_opt: ../opt/sf_adam_w__lr_5e-3.yml

    fad_model_names:
      - clap-2023
      - encodec-emb-48k

    use_rand_spline: true

    run_name: mss__s24d3D_rand__sm_16_1024__ase__ableton_10
