name: md
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - pip=25.2
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - auraloss==0.4.0
      - black==25.9.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - docstring-parser==0.17.0
      - einops==0.8.1
      - encodec==0.1.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hypy-utils==1.0.29
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonargparse==4.41.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - msclap==1.3.4
      - msgpack==1.1.1
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - neutone-sdk==1.4.3
      - nnaudio==0.3.3
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-ml-py==13.580.82
      - nvitop==1.5.3
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==11.3.0
      - pip-chill==1.0.3
      - platformdirs==4.4.0
      - pooch==1.8.2
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytokens==0.1.10
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - resampy==0.4.3
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - schedulefree==1.4.1
      - scikit-learn==1.7.2
      - scipy==1.11.4
      - sentry-sdk==2.39.0
      - shapely==2.1.2
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - soxr==1.0.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.2.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchlibrosa==0.1.0
      - torchmetrics==1.8.2
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.57.0
      - typeshed-client==2.8.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uv==0.8.22
      - wandb==0.22.1
      - werkzeug==3.1.3
      - yarl==1.20.1
