name: acid
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cuda-nvcc
  - cuda-nvrtc
  - cuda-version=12.4
  - pip:
    - auraloss
    - black
    - hypy_utils
    - jsonargparse[signatures]>=4.27.7
    - librosa
    - lightning
    - matplotlib
    - numba
    - numpy<2.0.0
    - nvitop
    - pandas
    - pip-chill
    - resampy
    - schedulefree
    - scipy
    - torch
    - torchaudio
    - torchvision
    - tensorboard
    - uv
    - wandb
    - git+https://github.com/Neutone/neutone_sdk.git@c69108d6ad11910afdc3ce4ead0a647456e2addb

# conda create -n acid python=3.10
# conda activate acid
# conda install -c conda-forge compilers
# conda install -c defaults cudatoolkit
# pip install uv
# uv add 'torch==2.2.2' lightning numba torchaudio torchvision auraloss black librosa matplotlib numpy nvitop pandas schedulefree 'scipy<=1.11.4' tensorboard wandb pip-chill dtw-python 'numpy<2.0.0' 'jsonargparse[signatures]' torchlibrosa shapely hypy_utils encodec transformers nnaudio resampy
# uv pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" --no-build-isolation
# uv pip install msclap --no-deps
