name: acid3
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.9
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.50.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.1
  - pip=25.1.1
  - python=3.10.18
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - auraloss==0.4.0
      - black==25.1.0
      - certifi==2025.7.9
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - docstring-parser==0.16
      - einops==0.8.1
      - encodec==0.1.1
      - filelock==3.18.0
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - hypy-utils==1.0.29
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonargparse==4.40.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - msclap==1.3.4
      - msgpack==1.1.1
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - neutone-sdk==1.4.3
      - nnaudio==0.3.3
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-ml-py==12.575.51
      - nvitop==1.5.1
      - packaging==25.0
      - pandas==2.3.1
      - pathspec==0.12.1
      - pillow==11.3.0
      - pip-chill==1.0.3
      - platformdirs==4.3.8
      - pooch==1.8.2
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - resampy==0.4.3
      - rpds-py==0.26.0
      - safetensors==0.5.3
      - schedulefree==1.4.1
      - scikit-learn==1.7.0
      - scipy==1.11.4
      - sentry-sdk==2.32.0
      - shapely==2.1.1
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchlibrosa==0.1.0
      - torchmetrics==1.7.4
      - torchvision==0.17.2
      - tqdm==4.67.1
      - transformers==4.53.2
      - typeshed-client==2.7.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uv==0.7.20
      - wandb==0.21.0
      - werkzeug==3.1.3
      - yarl==1.20.1

# conda create -n acid python=3.10
# conda activate acid
# conda install -c conda-forge compilers
# conda install -c defaults cudatoolkit
# pip install uv
# uv add 'torch==2.2.2' lightning numba torchaudio torchvision auraloss black librosa matplotlib numpy nvitop pandas schedulefree 'scipy<=1.11.4' tensorboard wandb pip-chill dtw-python 'numpy<2.0.0' 'jsonargparse[signatures]' torchlibrosa shapely hypy_utils encodec transformers nnaudio resampy
# uv pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" --no-build-isolation
# uv pip install msclap --no-deps


# uv pip install 'torch==2.2.2' lightning numba torchaudio torchvision auraloss black librosa matplotlib numpy nvitop pandas schedulefree 'scipy<=1.11.4' tensorboard wandb pip-chill 'numpy<2.0.0' 'jsonargparse[signatures]' torchlibrosa shapely hypy_utils encodec transformers nnaudio resampy jsonschema 'git+https://github.com/Neutone/neutone_sdk.git'
# uv pip install msclap --no-deps
# uv pip install 'git+https://github.com/Neutone/neutone_sdk.git' --no-deps
