class_path: feature_extraction.LogMelSpecFeatureExtractor
init_args:
  sr: 48000
  n_fft: 1024
  hop_len: 32
  n_mels: 128
  normalized: false
  center: true
  use_delta: true
  use_delta_delta: true
  delta_win_ms: 50
  freq_mask_amount: 0.0
  eps: 1e-4
