class_path: models.Spectral2DCNN
init_args:
  fe: log_mel_spec_dd50.yml
  in_ch: 3
  kernel_size: [5, 7]
  out_channels: [64, 64, 64, 64, 64, 64]
  temp_dilations: [1, 4, 16, 64, 256, 512]
  pool_size: [2, 1]
  use_ln: true
  temp_params:
    add_lfo:
      dim: 16
      act: softmax
      is_spline: false
      use_alpha_noise: false
      adapt_dim: 0
    sub_lfo:
      dim: 1
      act: none
      is_spline: true
      n_segments: 36
      degree: 3
      is_c1_cont: false
      is_bounded: false
      use_alpha_noise: false
      use_alpha_linear: true
      adapt_dim: 5
      adapt_act: none
      adapt_use_latent: false
      adapt_use_separate: true
    env:
      dim: 1
      act: none
      is_spline: true
      n_segments: 36
      degree: 3
      is_c1_cont: false
      is_bounded: true
      use_alpha_noise: false
      use_alpha_linear: true
      adapt_dim: 0
  global_param_names: []
  dropout: 0.0
  n_frames: 4501
  cnn_act: prelu
  fc_act: prelu
  noise_std: 0.33
