custom:
  project_name: mod_discovery
  model_name: mss__frame_8_hz__sm_16_1024
  dataset_name: serum__BA_both_lfo_10
  cpu_batch_size: 5
  use_wandb_cpu: false
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [5]
  max_epochs: 30
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5

data:
  class_path: mod_discovery.data_modules.SerumDataModule
  init_args:
    batch_size: 32
    ac: misc/audio_config.yml
    data_dir: ../data/serum-nsynth-v1
#    data_dir: data/serum-nsynth-v1
    preset_params_path: ../data/preset_params_v2.json
#    preset_params_path: data/preset_params_v2.json
    split_train: 0.6
    split_val: 0.2
    num_workers: 4
    fname_keywords:
      - BA Access 2 Mthrshp Denied
      - BA BitterBot
      - BA Deth reece
      - BA Gritter
      - BA Hoo
      - BA Le Gigante
      - BA Modulated Chomper
      - BA SCREAM Wobble 01
      - BA Sludgecrank
      - BA Wide Eyed Reese

model:
  class_path: mod_discovery.lightning.PreprocLightningModule
  init_args:
    ac: misc/audio_config.yml
    spectral_visualizer: misc/log_mel_spec.yml
    model: models/spectral_2dcnn_dd50__ase__sm_frame_8_hz.yml
    temp_param_names_hat:
      - add_lfo
      - sub_lfo
      - env
    interp_temp_param_names_hat:
      - add_lfo
      - env
    synth_hat: synths/synth__ase__sm.yml
    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    synth_opt: ../opt/sf_adam_w__lr_5e-2.yml
    model_opt: ../opt/sf_adam_w__lr_5e-3.yml
    fad_model_names:
      - clap-2023
      - encodec-emb-48k

    run_name: mss__frame_8_hz__sm_16_1024__serum__BA_both_lfo_10
