class_path: feature_extraction.LogMelSpecFeatureExtractor
init_args:
  sr: 16000
  n_fft: 1024
  hop_len: 32
  n_mels: 128
  normalized: false
  center: true
  use_delta: false
  use_delta_delta: false
  freq_mask_amount: 0.0
  eps: 1e-4
