class_path: models.Spectral2DCNN
init_args:
  fe: log_mel_spec_dd50.yml
  in_ch: 3
#  in_ch: 6
  kernel_size: [5, 7]
  out_channels: [64, 64, 64, 64, 64, 64]
#  temp_dilations: [1, 4, 16, 64, 256, 512]
  temp_dilations: [1, 4, 16, 32, 64, 128]
  pool_size: [2, 1]
  use_ln: true
  temp_params:
    add_lfo:
      dim: 1
      act: none
      is_spline: true
      n_segments: 12
      degree: 3
      is_c1_cont: false
      is_bounded: true
      adapt_dim: 0
  global_param_names: []
#  dropout: 0.25
  dropout: 0.0
  n_frames: 1501
