custom:
  project_name: acid_ddsp_2
  model_name: mss__s24d3D_nn__lfo
  dataset_name: lfo__ase__fm_fold
  cpu_batch_size: 5
  use_wandb_cpu: false
#  use_wandb_gpu: true
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [0]
  max_epochs: 30
  num_sanity_val_steps: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.SeedDataModule
  init_args:
    batch_size: 32
    ac: audio_config.yml
    n_seeds: 1024
    mod_sig_gens:
      - class_path: acid_ddsp.modulations.ModSignalGenRandomBezier1D
        init_args:
          min_n_seg: 1
          max_n_seg: 8
          min_degree: 1
          max_degree: 3
          min_seg_interval_frac: 0.5
    global_param_names:
      - q
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    n_frames: 1501
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml
    synth: synth__ase__ddsp.yml
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    interp_temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    # model: spectral_2dcnn_dd50__ase__lfo.yml
    model: spectral_2dcnn_dd50__ase__sm.yml
    temp_param_names_hat:
      - add_lfo
      - sub_lfo
      - env
    interp_temp_param_names_hat:
      - add_lfo
      - sub_lfo
      - env
    synth_hat: synth__ase__ddsp.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false

    model_opt: ../opt/sf_adam_w__lr_5e-3.yml

    fad_model_names:
      - clap-2023
      - encodec-emb-48k
      - panns-cnn14-32k
      - panns-wavegram-logmel

    run_name: mss__s24d3D_nn__lfo__lfo__ase__fm_fold
