custom:
  project_name: acid_ddsp_2
  model_name: mss__frame_32_interp_36__sm_16_1024
  dataset_name: ableton__ase__fm_fold
  cpu_batch_size: 5
  use_wandb_cpu: false
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 30
  num_sanity_val_steps: 1
  gradient_clip_val: 0.5

data:
  class_path: acid_ddsp.data_modules.SeedDataModule
  init_args:
    batch_size: 32
    ac: audio_config.yml
    n_seeds: 1024
    mod_sig_gens:
      - class_path: acid_ddsp.modulations.ModSignalGenRandomBezier
        init_args:
          min_n_seg: 1
          max_n_seg: 8
          min_degree: 1
          max_degree: 3
          min_seg_interval_frac: 0.25
          softmax_tau: 0.25
          normalize: false
    global_param_names:
      - q
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env
    num_workers: 4

model:
  class_path: acid_ddsp.lightning.AcidDDSPLightingModule
  init_args:
    ac: audio_config.yml
    spectral_visualizer: log_mel_spec.yml

    synth: synth__ase.yml
    temp_param_names:
      - add_lfo
      - sub_lfo
      - env

    use_model: true
    model: spectral_2dcnn_dd50__ase__sm_frame_32_interp_36.yml
    temp_param_names_hat:
      - add_lfo
      - sub_lfo
      - env
    interp_temp_param_names_hat:
      - add_lfo
      - env
    synth_hat: synth__ase__sm.yml

    loss_func: auraloss.freq.MultiResolutionSTFTLoss
    use_p_loss: false

    run_name: mss__s12d3__frame_32_interp_36__ableton__ase__fm_fold

    synth_opt: ../opt/sf_adam_w__lr_5e-2.yml
    model_opt: ../opt/sf_adam_w__lr_5e-3.yml

    fad_model_names:
      - clap-2023
      - encodec-emb-24k
      - panns-cnn14-16k
      - panns-wavegram-logmel
