class_path: synths.ComposableSynth
init_args:
  ac: ../misc/audio_config.yml
  add_synth_module: ddsp_osc__harmonic.yml
  sub_synth_module: ddsp_osc__noise.yml
  add_lfo_name: add_lfo_adapted
  sub_lfo_name: sub_lfo_adapted